/**
 * generated by Xtext 2.15.0
 */
package br.com.poli;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RESTModelRuntimeModule /* implements AbstractRESTModelRuntimeModule  */{
}
