/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.ide;

import br.com.poli.RESTModelStandaloneSetup;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RESTModelIdeSetup extends RESTModelStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from RESTModelRuntimeModule to Module"
      + "\nType mismatch: cannot convert from RESTModelIdeModule to Module");
  }
}
