/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RESTModelIdeModule /* implements AbstractRESTModelIdeModule  */{
}
