/*
 * generated by Xtext 2.15.0
 */
package br.com.poli.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRESTModelScopeProvider extends DelegatingScopeProvider {
}
