/*
 * generated by Xtext 2.15.0
 */
package br.com.poli.ui.tests;

import br.com.poli.RESTModel.ui.internal.RESTModelActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RESTModelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RESTModelActivator.getInstance().getInjector("br.com.poli.RESTModel");
	}

}
