/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.ui.contentassist;

import br.com.poli.restModel.ui.contentassist.AbstractRestProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RestProposalProvider extends AbstractRestProposalProvider {
}
