/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.rESTModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.com.poli.rESTModel.Field#getAtrib <em>Atrib</em>}</li>
 *   <li>{@link br.com.poli.rESTModel.Field#getMeth <em>Meth</em>}</li>
 * </ul>
 *
 * @see br.com.poli.rESTModel.RESTModelPackage#getField()
 * @model
 * @generated
 */
public interface Field extends EObject
{
  /**
   * Returns the value of the '<em><b>Atrib</b></em>' containment reference list.
   * The list contents are of type {@link br.com.poli.rESTModel.Atrib}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atrib</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atrib</em>' containment reference list.
   * @see br.com.poli.rESTModel.RESTModelPackage#getField_Atrib()
   * @model containment="true"
   * @generated
   */
  EList<Atrib> getAtrib();

  /**
   * Returns the value of the '<em><b>Meth</b></em>' containment reference list.
   * The list contents are of type {@link br.com.poli.rESTModel.Method}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Meth</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Meth</em>' containment reference list.
   * @see br.com.poli.rESTModel.RESTModelPackage#getField_Meth()
   * @model containment="true"
   * @generated
   */
  EList<Method> getMeth();

} // Field
