/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.rESTModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.com.poli.rESTModel.MethodBody#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see br.com.poli.rESTModel.RESTModelPackage#getMethodBody()
 * @model
 * @generated
 */
public interface MethodBody extends EObject
{
  /**
   * Returns the value of the '<em><b>Body</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' attribute list.
   * @see br.com.poli.rESTModel.RESTModelPackage#getMethodBody_Body()
   * @model unique="false"
   * @generated
   */
  EList<String> getBody();

} // MethodBody
