/*
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.ui;

import br.com.poli.restModel.ui.internal.RestModelActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RestExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RestModelActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RestModelActivator activator = RestModelActivator.getInstance();
		return activator != null ? activator.getInjector(RestModelActivator.BR_COM_POLI_RESTMODEL_REST) : null;
	}

}
