/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.rest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atrib</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.com.poli.restModel.rest.Atrib#getAtribName <em>Atrib Name</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Atrib#getTipo <em>Tipo</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Atrib#getValueInt <em>Value Int</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Atrib#getValueBool <em>Value Bool</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Atrib#getValueFlo <em>Value Flo</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Atrib#getValueStr <em>Value Str</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Atrib#getValueChr <em>Value Chr</em>}</li>
 * </ul>
 *
 * @see br.com.poli.restModel.rest.RestPackage#getAtrib()
 * @model
 * @generated
 */
public interface Atrib extends EObject
{
  /**
   * Returns the value of the '<em><b>Atrib Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atrib Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atrib Name</em>' attribute.
   * @see #setAtribName(String)
   * @see br.com.poli.restModel.rest.RestPackage#getAtrib_AtribName()
   * @model
   * @generated
   */
  String getAtribName();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Atrib#getAtribName <em>Atrib Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atrib Name</em>' attribute.
   * @see #getAtribName()
   * @generated
   */
  void setAtribName(String value);

  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tipo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see #setTipo(String)
   * @see br.com.poli.restModel.rest.RestPackage#getAtrib_Tipo()
   * @model
   * @generated
   */
  String getTipo();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Atrib#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see #getTipo()
   * @generated
   */
  void setTipo(String value);

  /**
   * Returns the value of the '<em><b>Value Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Int</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Int</em>' attribute.
   * @see #setValueInt(int)
   * @see br.com.poli.restModel.rest.RestPackage#getAtrib_ValueInt()
   * @model
   * @generated
   */
  int getValueInt();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Atrib#getValueInt <em>Value Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Int</em>' attribute.
   * @see #getValueInt()
   * @generated
   */
  void setValueInt(int value);

  /**
   * Returns the value of the '<em><b>Value Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Bool</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Bool</em>' attribute.
   * @see #setValueBool(String)
   * @see br.com.poli.restModel.rest.RestPackage#getAtrib_ValueBool()
   * @model
   * @generated
   */
  String getValueBool();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Atrib#getValueBool <em>Value Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Bool</em>' attribute.
   * @see #getValueBool()
   * @generated
   */
  void setValueBool(String value);

  /**
   * Returns the value of the '<em><b>Value Flo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Flo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Flo</em>' attribute.
   * @see #setValueFlo(float)
   * @see br.com.poli.restModel.rest.RestPackage#getAtrib_ValueFlo()
   * @model
   * @generated
   */
  float getValueFlo();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Atrib#getValueFlo <em>Value Flo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Flo</em>' attribute.
   * @see #getValueFlo()
   * @generated
   */
  void setValueFlo(float value);

  /**
   * Returns the value of the '<em><b>Value Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Str</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Str</em>' attribute.
   * @see #setValueStr(String)
   * @see br.com.poli.restModel.rest.RestPackage#getAtrib_ValueStr()
   * @model
   * @generated
   */
  String getValueStr();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Atrib#getValueStr <em>Value Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Str</em>' attribute.
   * @see #getValueStr()
   * @generated
   */
  void setValueStr(String value);

  /**
   * Returns the value of the '<em><b>Value Chr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Chr</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Chr</em>' attribute.
   * @see #setValueChr(char)
   * @see br.com.poli.restModel.rest.RestPackage#getAtrib_ValueChr()
   * @model
   * @generated
   */
  char getValueChr();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Atrib#getValueChr <em>Value Chr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Chr</em>' attribute.
   * @see #getValueChr()
   * @generated
   */
  void setValueChr(char value);

} // Atrib
