/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.rest;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.com.poli.restModel.rest.Method#getMName <em>MName</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Method#getPar <em>Par</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Method#getTipo <em>Tipo</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Method#getImplem <em>Implem</em>}</li>
 * </ul>
 *
 * @see br.com.poli.restModel.rest.RestPackage#getMethod()
 * @model
 * @generated
 */
public interface Method extends EObject
{
  /**
   * Returns the value of the '<em><b>MName</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>MName</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>MName</em>' attribute.
   * @see #setMName(String)
   * @see br.com.poli.restModel.rest.RestPackage#getMethod_MName()
   * @model
   * @generated
   */
  String getMName();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Method#getMName <em>MName</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>MName</em>' attribute.
   * @see #getMName()
   * @generated
   */
  void setMName(String value);

  /**
   * Returns the value of the '<em><b>Par</b></em>' containment reference list.
   * The list contents are of type {@link br.com.poli.restModel.rest.Parm}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Par</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Par</em>' containment reference list.
   * @see br.com.poli.restModel.rest.RestPackage#getMethod_Par()
   * @model containment="true"
   * @generated
   */
  EList<Parm> getPar();

  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tipo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see #setTipo(String)
   * @see br.com.poli.restModel.rest.RestPackage#getMethod_Tipo()
   * @model
   * @generated
   */
  String getTipo();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Method#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see #getTipo()
   * @generated
   */
  void setTipo(String value);

  /**
   * Returns the value of the '<em><b>Implem</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Implem</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Implem</em>' attribute.
   * @see #setImplem(String)
   * @see br.com.poli.restModel.rest.RestPackage#getMethod_Implem()
   * @model
   * @generated
   */
  String getImplem();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Method#getImplem <em>Implem</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Implem</em>' attribute.
   * @see #getImplem()
   * @generated
   */
  void setImplem(String value);

} // Method
