/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.rest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parm</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.com.poli.restModel.rest.Parm#getAtribName <em>Atrib Name</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Parm#getTipo_atri <em>Tipo atri</em>}</li>
 * </ul>
 *
 * @see br.com.poli.restModel.rest.RestPackage#getParm()
 * @model
 * @generated
 */
public interface Parm extends EObject
{
  /**
   * Returns the value of the '<em><b>Atrib Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atrib Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atrib Name</em>' attribute.
   * @see #setAtribName(String)
   * @see br.com.poli.restModel.rest.RestPackage#getParm_AtribName()
   * @model
   * @generated
   */
  String getAtribName();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Parm#getAtribName <em>Atrib Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atrib Name</em>' attribute.
   * @see #getAtribName()
   * @generated
   */
  void setAtribName(String value);

  /**
   * Returns the value of the '<em><b>Tipo atri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tipo atri</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo atri</em>' attribute.
   * @see #setTipo_atri(String)
   * @see br.com.poli.restModel.rest.RestPackage#getParm_Tipo_atri()
   * @model
   * @generated
   */
  String getTipo_atri();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Parm#getTipo_atri <em>Tipo atri</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo atri</em>' attribute.
   * @see #getTipo_atri()
   * @generated
   */
  void setTipo_atri(String value);

} // Parm
