/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.rest;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see br.com.poli.restModel.rest.RestFactory
 * @model kind="package"
 * @generated
 */
public interface RestPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "rest";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.com.br/poli/restModel/Rest";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "rest";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RestPackage eINSTANCE = br.com.poli.restModel.rest.impl.RestPackageImpl.init();

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.ModelImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__BODY = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.BodyImpl <em>Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.BodyImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getBody()
   * @generated
   */
  int BODY = 1;

  /**
   * The feature id for the '<em><b>Elem</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY__ELEM = 0;

  /**
   * The feature id for the '<em><b>Glob Atrib</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY__GLOB_ATRIB = 1;

  /**
   * The number of structural features of the '<em>Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.ElemImpl <em>Elem</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.ElemImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getElem()
   * @generated
   */
  int ELEM = 2;

  /**
   * The feature id for the '<em><b>Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEM__CLASS_NAME = 0;

  /**
   * The feature id for the '<em><b>Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEM__PACKAGE = 1;

  /**
   * The feature id for the '<em><b>Atrib</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEM__ATRIB = 2;

  /**
   * The number of structural features of the '<em>Elem</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.AtribImpl <em>Atrib</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.AtribImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getAtrib()
   * @generated
   */
  int ATRIB = 3;

  /**
   * The feature id for the '<em><b>Atrib Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB__ATRIB_NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB__TIPO = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB__VALUE = 2;

  /**
   * The number of structural features of the '<em>Atrib</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.GlobAtribImpl <em>Glob Atrib</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.GlobAtribImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getGlobAtrib()
   * @generated
   */
  int GLOB_ATRIB = 4;

  /**
   * The feature id for the '<em><b>Atrib Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOB_ATRIB__ATRIB_NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOB_ATRIB__TIPO = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOB_ATRIB__VALUE = 2;

  /**
   * The number of structural features of the '<em>Glob Atrib</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOB_ATRIB_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.ValuesImpl <em>Values</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.ValuesImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getValues()
   * @generated
   */
  int VALUES = 5;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUES__ID = 0;

  /**
   * The feature id for the '<em><b>Id B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUES__ID_B = 1;

  /**
   * The feature id for the '<em><b>Id F</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUES__ID_F = 2;

  /**
   * The feature id for the '<em><b>Id S</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUES__ID_S = 3;

  /**
   * The feature id for the '<em><b>Id C</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUES__ID_C = 4;

  /**
   * The feature id for the '<em><b>Id T</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUES__ID_T = 5;

  /**
   * The feature id for the '<em><b>Par</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUES__PAR = 6;

  /**
   * The number of structural features of the '<em>Values</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUES_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.ParmImpl <em>Parm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.ParmImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getParm()
   * @generated
   */
  int PARM = 6;

  /**
   * The feature id for the '<em><b>Atrib Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARM__ATRIB_NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo atri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARM__TIPO_ATRI = 1;

  /**
   * The number of structural features of the '<em>Parm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARM_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see br.com.poli.restModel.rest.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link br.com.poli.restModel.rest.Model#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see br.com.poli.restModel.rest.Model#getBody()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Body();

  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Body <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Body</em>'.
   * @see br.com.poli.restModel.rest.Body
   * @generated
   */
  EClass getBody();

  /**
   * Returns the meta object for the containment reference '{@link br.com.poli.restModel.rest.Body#getElem <em>Elem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elem</em>'.
   * @see br.com.poli.restModel.rest.Body#getElem()
   * @see #getBody()
   * @generated
   */
  EReference getBody_Elem();

  /**
   * Returns the meta object for the containment reference '{@link br.com.poli.restModel.rest.Body#getGlobAtrib <em>Glob Atrib</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Glob Atrib</em>'.
   * @see br.com.poli.restModel.rest.Body#getGlobAtrib()
   * @see #getBody()
   * @generated
   */
  EReference getBody_GlobAtrib();

  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Elem <em>Elem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Elem</em>'.
   * @see br.com.poli.restModel.rest.Elem
   * @generated
   */
  EClass getElem();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Elem#getClassName <em>Class Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Class Name</em>'.
   * @see br.com.poli.restModel.rest.Elem#getClassName()
   * @see #getElem()
   * @generated
   */
  EAttribute getElem_ClassName();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Elem#getPackage <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Package</em>'.
   * @see br.com.poli.restModel.rest.Elem#getPackage()
   * @see #getElem()
   * @generated
   */
  EAttribute getElem_Package();

  /**
   * Returns the meta object for the containment reference list '{@link br.com.poli.restModel.rest.Elem#getAtrib <em>Atrib</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Atrib</em>'.
   * @see br.com.poli.restModel.rest.Elem#getAtrib()
   * @see #getElem()
   * @generated
   */
  EReference getElem_Atrib();

  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Atrib <em>Atrib</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atrib</em>'.
   * @see br.com.poli.restModel.rest.Atrib
   * @generated
   */
  EClass getAtrib();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Atrib#getAtribName <em>Atrib Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Atrib Name</em>'.
   * @see br.com.poli.restModel.rest.Atrib#getAtribName()
   * @see #getAtrib()
   * @generated
   */
  EAttribute getAtrib_AtribName();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Atrib#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see br.com.poli.restModel.rest.Atrib#getTipo()
   * @see #getAtrib()
   * @generated
   */
  EAttribute getAtrib_Tipo();

  /**
   * Returns the meta object for the containment reference '{@link br.com.poli.restModel.rest.Atrib#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see br.com.poli.restModel.rest.Atrib#getValue()
   * @see #getAtrib()
   * @generated
   */
  EReference getAtrib_Value();

  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.GlobAtrib <em>Glob Atrib</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Glob Atrib</em>'.
   * @see br.com.poli.restModel.rest.GlobAtrib
   * @generated
   */
  EClass getGlobAtrib();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.GlobAtrib#getAtribName <em>Atrib Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Atrib Name</em>'.
   * @see br.com.poli.restModel.rest.GlobAtrib#getAtribName()
   * @see #getGlobAtrib()
   * @generated
   */
  EAttribute getGlobAtrib_AtribName();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.GlobAtrib#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see br.com.poli.restModel.rest.GlobAtrib#getTipo()
   * @see #getGlobAtrib()
   * @generated
   */
  EAttribute getGlobAtrib_Tipo();

  /**
   * Returns the meta object for the containment reference '{@link br.com.poli.restModel.rest.GlobAtrib#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see br.com.poli.restModel.rest.GlobAtrib#getValue()
   * @see #getGlobAtrib()
   * @generated
   */
  EReference getGlobAtrib_Value();

  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Values <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Values</em>'.
   * @see br.com.poli.restModel.rest.Values
   * @generated
   */
  EClass getValues();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Values#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see br.com.poli.restModel.rest.Values#getId()
   * @see #getValues()
   * @generated
   */
  EAttribute getValues_Id();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Values#getIdB <em>Id B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id B</em>'.
   * @see br.com.poli.restModel.rest.Values#getIdB()
   * @see #getValues()
   * @generated
   */
  EAttribute getValues_IdB();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Values#getIdF <em>Id F</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id F</em>'.
   * @see br.com.poli.restModel.rest.Values#getIdF()
   * @see #getValues()
   * @generated
   */
  EAttribute getValues_IdF();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Values#getIdS <em>Id S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id S</em>'.
   * @see br.com.poli.restModel.rest.Values#getIdS()
   * @see #getValues()
   * @generated
   */
  EAttribute getValues_IdS();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Values#getIdC <em>Id C</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id C</em>'.
   * @see br.com.poli.restModel.rest.Values#getIdC()
   * @see #getValues()
   * @generated
   */
  EAttribute getValues_IdC();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Values#getIdT <em>Id T</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id T</em>'.
   * @see br.com.poli.restModel.rest.Values#getIdT()
   * @see #getValues()
   * @generated
   */
  EAttribute getValues_IdT();

  /**
   * Returns the meta object for the attribute list '{@link br.com.poli.restModel.rest.Values#getPar <em>Par</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Par</em>'.
   * @see br.com.poli.restModel.rest.Values#getPar()
   * @see #getValues()
   * @generated
   */
  EAttribute getValues_Par();

  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Parm <em>Parm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parm</em>'.
   * @see br.com.poli.restModel.rest.Parm
   * @generated
   */
  EClass getParm();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Parm#getAtribName <em>Atrib Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Atrib Name</em>'.
   * @see br.com.poli.restModel.rest.Parm#getAtribName()
   * @see #getParm()
   * @generated
   */
  EAttribute getParm_AtribName();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Parm#getTipo_atri <em>Tipo atri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo atri</em>'.
   * @see br.com.poli.restModel.rest.Parm#getTipo_atri()
   * @see #getParm()
   * @generated
   */
  EAttribute getParm_Tipo_atri();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RestFactory getRestFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.ModelImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__BODY = eINSTANCE.getModel_Body();

    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.BodyImpl <em>Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.BodyImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getBody()
     * @generated
     */
    EClass BODY = eINSTANCE.getBody();

    /**
     * The meta object literal for the '<em><b>Elem</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BODY__ELEM = eINSTANCE.getBody_Elem();

    /**
     * The meta object literal for the '<em><b>Glob Atrib</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BODY__GLOB_ATRIB = eINSTANCE.getBody_GlobAtrib();

    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.ElemImpl <em>Elem</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.ElemImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getElem()
     * @generated
     */
    EClass ELEM = eINSTANCE.getElem();

    /**
     * The meta object literal for the '<em><b>Class Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEM__CLASS_NAME = eINSTANCE.getElem_ClassName();

    /**
     * The meta object literal for the '<em><b>Package</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEM__PACKAGE = eINSTANCE.getElem_Package();

    /**
     * The meta object literal for the '<em><b>Atrib</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEM__ATRIB = eINSTANCE.getElem_Atrib();

    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.AtribImpl <em>Atrib</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.AtribImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getAtrib()
     * @generated
     */
    EClass ATRIB = eINSTANCE.getAtrib();

    /**
     * The meta object literal for the '<em><b>Atrib Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIB__ATRIB_NAME = eINSTANCE.getAtrib_AtribName();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIB__TIPO = eINSTANCE.getAtrib_Tipo();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIB__VALUE = eINSTANCE.getAtrib_Value();

    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.GlobAtribImpl <em>Glob Atrib</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.GlobAtribImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getGlobAtrib()
     * @generated
     */
    EClass GLOB_ATRIB = eINSTANCE.getGlobAtrib();

    /**
     * The meta object literal for the '<em><b>Atrib Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GLOB_ATRIB__ATRIB_NAME = eINSTANCE.getGlobAtrib_AtribName();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GLOB_ATRIB__TIPO = eINSTANCE.getGlobAtrib_Tipo();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GLOB_ATRIB__VALUE = eINSTANCE.getGlobAtrib_Value();

    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.ValuesImpl <em>Values</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.ValuesImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getValues()
     * @generated
     */
    EClass VALUES = eINSTANCE.getValues();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUES__ID = eINSTANCE.getValues_Id();

    /**
     * The meta object literal for the '<em><b>Id B</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUES__ID_B = eINSTANCE.getValues_IdB();

    /**
     * The meta object literal for the '<em><b>Id F</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUES__ID_F = eINSTANCE.getValues_IdF();

    /**
     * The meta object literal for the '<em><b>Id S</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUES__ID_S = eINSTANCE.getValues_IdS();

    /**
     * The meta object literal for the '<em><b>Id C</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUES__ID_C = eINSTANCE.getValues_IdC();

    /**
     * The meta object literal for the '<em><b>Id T</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUES__ID_T = eINSTANCE.getValues_IdT();

    /**
     * The meta object literal for the '<em><b>Par</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUES__PAR = eINSTANCE.getValues_Par();

    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.ParmImpl <em>Parm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.ParmImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getParm()
     * @generated
     */
    EClass PARM = eINSTANCE.getParm();

    /**
     * The meta object literal for the '<em><b>Atrib Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARM__ATRIB_NAME = eINSTANCE.getParm_AtribName();

    /**
     * The meta object literal for the '<em><b>Tipo atri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARM__TIPO_ATRI = eINSTANCE.getParm_Tipo_atri();

  }

} //RestPackage
