/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.rest;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see br.com.poli.restModel.rest.RestFactory
 * @model kind="package"
 * @generated
 */
public interface RestPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "rest";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.com.br/poli/restModel/Rest";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "rest";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RestPackage eINSTANCE = br.com.poli.restModel.rest.impl.RestPackageImpl.init();

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.ModelImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__BODY = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.BodyImpl <em>Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.BodyImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getBody()
   * @generated
   */
  int BODY = 1;

  /**
   * The feature id for the '<em><b>Elem</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY__ELEM = 0;

  /**
   * The feature id for the '<em><b>Glob Atrib</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY__GLOB_ATRIB = 1;

  /**
   * The number of structural features of the '<em>Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.ElemImpl <em>Elem</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.ElemImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getElem()
   * @generated
   */
  int ELEM = 2;

  /**
   * The feature id for the '<em><b>Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEM__CLASS_NAME = 0;

  /**
   * The feature id for the '<em><b>Field</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEM__FIELD = 1;

  /**
   * The number of structural features of the '<em>Elem</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.FieldImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getField()
   * @generated
   */
  int FIELD = 3;

  /**
   * The feature id for the '<em><b>Atrib</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__ATRIB = 0;

  /**
   * The feature id for the '<em><b>Method</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__METHOD = 1;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.MethodImpl <em>Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.MethodImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getMethod()
   * @generated
   */
  int METHOD = 4;

  /**
   * The feature id for the '<em><b>MName</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__MNAME = 0;

  /**
   * The feature id for the '<em><b>Par</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__PAR = 1;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__TIPO = 2;

  /**
   * The feature id for the '<em><b>Implem</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__IMPLEM = 3;

  /**
   * The number of structural features of the '<em>Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.ParmImpl <em>Parm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.ParmImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getParm()
   * @generated
   */
  int PARM = 5;

  /**
   * The feature id for the '<em><b>Atrib Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARM__ATRIB_NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo atri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARM__TIPO_ATRI = 1;

  /**
   * The number of structural features of the '<em>Parm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.com.poli.restModel.rest.impl.AtribImpl <em>Atrib</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.poli.restModel.rest.impl.AtribImpl
   * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getAtrib()
   * @generated
   */
  int ATRIB = 6;

  /**
   * The feature id for the '<em><b>Atrib Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB__ATRIB_NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB__TIPO = 1;

  /**
   * The feature id for the '<em><b>Value Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB__VALUE_INT = 2;

  /**
   * The feature id for the '<em><b>Value Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB__VALUE_BOOL = 3;

  /**
   * The feature id for the '<em><b>Value Flo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB__VALUE_FLO = 4;

  /**
   * The feature id for the '<em><b>Value Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB__VALUE_STR = 5;

  /**
   * The feature id for the '<em><b>Value Chr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB__VALUE_CHR = 6;

  /**
   * The number of structural features of the '<em>Atrib</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIB_FEATURE_COUNT = 7;


  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see br.com.poli.restModel.rest.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link br.com.poli.restModel.rest.Model#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see br.com.poli.restModel.rest.Model#getBody()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Body();

  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Body <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Body</em>'.
   * @see br.com.poli.restModel.rest.Body
   * @generated
   */
  EClass getBody();

  /**
   * Returns the meta object for the containment reference list '{@link br.com.poli.restModel.rest.Body#getElem <em>Elem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elem</em>'.
   * @see br.com.poli.restModel.rest.Body#getElem()
   * @see #getBody()
   * @generated
   */
  EReference getBody_Elem();

  /**
   * Returns the meta object for the containment reference list '{@link br.com.poli.restModel.rest.Body#getGlobAtrib <em>Glob Atrib</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Glob Atrib</em>'.
   * @see br.com.poli.restModel.rest.Body#getGlobAtrib()
   * @see #getBody()
   * @generated
   */
  EReference getBody_GlobAtrib();

  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Elem <em>Elem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Elem</em>'.
   * @see br.com.poli.restModel.rest.Elem
   * @generated
   */
  EClass getElem();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Elem#getClassName <em>Class Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Class Name</em>'.
   * @see br.com.poli.restModel.rest.Elem#getClassName()
   * @see #getElem()
   * @generated
   */
  EAttribute getElem_ClassName();

  /**
   * Returns the meta object for the containment reference list '{@link br.com.poli.restModel.rest.Elem#getField <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Field</em>'.
   * @see br.com.poli.restModel.rest.Elem#getField()
   * @see #getElem()
   * @generated
   */
  EReference getElem_Field();

  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see br.com.poli.restModel.rest.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the containment reference '{@link br.com.poli.restModel.rest.Field#getAtrib <em>Atrib</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atrib</em>'.
   * @see br.com.poli.restModel.rest.Field#getAtrib()
   * @see #getField()
   * @generated
   */
  EReference getField_Atrib();

  /**
   * Returns the meta object for the containment reference '{@link br.com.poli.restModel.rest.Field#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Method</em>'.
   * @see br.com.poli.restModel.rest.Field#getMethod()
   * @see #getField()
   * @generated
   */
  EReference getField_Method();

  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Method <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method</em>'.
   * @see br.com.poli.restModel.rest.Method
   * @generated
   */
  EClass getMethod();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Method#getMName <em>MName</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>MName</em>'.
   * @see br.com.poli.restModel.rest.Method#getMName()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_MName();

  /**
   * Returns the meta object for the containment reference list '{@link br.com.poli.restModel.rest.Method#getPar <em>Par</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Par</em>'.
   * @see br.com.poli.restModel.rest.Method#getPar()
   * @see #getMethod()
   * @generated
   */
  EReference getMethod_Par();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Method#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see br.com.poli.restModel.rest.Method#getTipo()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Tipo();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Method#getImplem <em>Implem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Implem</em>'.
   * @see br.com.poli.restModel.rest.Method#getImplem()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Implem();

  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Parm <em>Parm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parm</em>'.
   * @see br.com.poli.restModel.rest.Parm
   * @generated
   */
  EClass getParm();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Parm#getAtribName <em>Atrib Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Atrib Name</em>'.
   * @see br.com.poli.restModel.rest.Parm#getAtribName()
   * @see #getParm()
   * @generated
   */
  EAttribute getParm_AtribName();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Parm#getTipo_atri <em>Tipo atri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo atri</em>'.
   * @see br.com.poli.restModel.rest.Parm#getTipo_atri()
   * @see #getParm()
   * @generated
   */
  EAttribute getParm_Tipo_atri();

  /**
   * Returns the meta object for class '{@link br.com.poli.restModel.rest.Atrib <em>Atrib</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atrib</em>'.
   * @see br.com.poli.restModel.rest.Atrib
   * @generated
   */
  EClass getAtrib();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Atrib#getAtribName <em>Atrib Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Atrib Name</em>'.
   * @see br.com.poli.restModel.rest.Atrib#getAtribName()
   * @see #getAtrib()
   * @generated
   */
  EAttribute getAtrib_AtribName();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Atrib#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see br.com.poli.restModel.rest.Atrib#getTipo()
   * @see #getAtrib()
   * @generated
   */
  EAttribute getAtrib_Tipo();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Atrib#getValueInt <em>Value Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value Int</em>'.
   * @see br.com.poli.restModel.rest.Atrib#getValueInt()
   * @see #getAtrib()
   * @generated
   */
  EAttribute getAtrib_ValueInt();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Atrib#getValueBool <em>Value Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value Bool</em>'.
   * @see br.com.poli.restModel.rest.Atrib#getValueBool()
   * @see #getAtrib()
   * @generated
   */
  EAttribute getAtrib_ValueBool();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Atrib#getValueFlo <em>Value Flo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value Flo</em>'.
   * @see br.com.poli.restModel.rest.Atrib#getValueFlo()
   * @see #getAtrib()
   * @generated
   */
  EAttribute getAtrib_ValueFlo();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Atrib#getValueStr <em>Value Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value Str</em>'.
   * @see br.com.poli.restModel.rest.Atrib#getValueStr()
   * @see #getAtrib()
   * @generated
   */
  EAttribute getAtrib_ValueStr();

  /**
   * Returns the meta object for the attribute '{@link br.com.poli.restModel.rest.Atrib#getValueChr <em>Value Chr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value Chr</em>'.
   * @see br.com.poli.restModel.rest.Atrib#getValueChr()
   * @see #getAtrib()
   * @generated
   */
  EAttribute getAtrib_ValueChr();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RestFactory getRestFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.ModelImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__BODY = eINSTANCE.getModel_Body();

    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.BodyImpl <em>Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.BodyImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getBody()
     * @generated
     */
    EClass BODY = eINSTANCE.getBody();

    /**
     * The meta object literal for the '<em><b>Elem</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BODY__ELEM = eINSTANCE.getBody_Elem();

    /**
     * The meta object literal for the '<em><b>Glob Atrib</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BODY__GLOB_ATRIB = eINSTANCE.getBody_GlobAtrib();

    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.ElemImpl <em>Elem</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.ElemImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getElem()
     * @generated
     */
    EClass ELEM = eINSTANCE.getElem();

    /**
     * The meta object literal for the '<em><b>Class Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEM__CLASS_NAME = eINSTANCE.getElem_ClassName();

    /**
     * The meta object literal for the '<em><b>Field</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEM__FIELD = eINSTANCE.getElem_Field();

    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.FieldImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Atrib</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__ATRIB = eINSTANCE.getField_Atrib();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__METHOD = eINSTANCE.getField_Method();

    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.MethodImpl <em>Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.MethodImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getMethod()
     * @generated
     */
    EClass METHOD = eINSTANCE.getMethod();

    /**
     * The meta object literal for the '<em><b>MName</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__MNAME = eINSTANCE.getMethod_MName();

    /**
     * The meta object literal for the '<em><b>Par</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD__PAR = eINSTANCE.getMethod_Par();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__TIPO = eINSTANCE.getMethod_Tipo();

    /**
     * The meta object literal for the '<em><b>Implem</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__IMPLEM = eINSTANCE.getMethod_Implem();

    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.ParmImpl <em>Parm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.ParmImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getParm()
     * @generated
     */
    EClass PARM = eINSTANCE.getParm();

    /**
     * The meta object literal for the '<em><b>Atrib Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARM__ATRIB_NAME = eINSTANCE.getParm_AtribName();

    /**
     * The meta object literal for the '<em><b>Tipo atri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARM__TIPO_ATRI = eINSTANCE.getParm_Tipo_atri();

    /**
     * The meta object literal for the '{@link br.com.poli.restModel.rest.impl.AtribImpl <em>Atrib</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.poli.restModel.rest.impl.AtribImpl
     * @see br.com.poli.restModel.rest.impl.RestPackageImpl#getAtrib()
     * @generated
     */
    EClass ATRIB = eINSTANCE.getAtrib();

    /**
     * The meta object literal for the '<em><b>Atrib Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIB__ATRIB_NAME = eINSTANCE.getAtrib_AtribName();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIB__TIPO = eINSTANCE.getAtrib_Tipo();

    /**
     * The meta object literal for the '<em><b>Value Int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIB__VALUE_INT = eINSTANCE.getAtrib_ValueInt();

    /**
     * The meta object literal for the '<em><b>Value Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIB__VALUE_BOOL = eINSTANCE.getAtrib_ValueBool();

    /**
     * The meta object literal for the '<em><b>Value Flo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIB__VALUE_FLO = eINSTANCE.getAtrib_ValueFlo();

    /**
     * The meta object literal for the '<em><b>Value Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIB__VALUE_STR = eINSTANCE.getAtrib_ValueStr();

    /**
     * The meta object literal for the '<em><b>Value Chr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIB__VALUE_CHR = eINSTANCE.getAtrib_ValueChr();

  }

} //RestPackage
