/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.rest;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Values</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.com.poli.restModel.rest.Values#getId <em>Id</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Values#getIdB <em>Id B</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Values#getIdF <em>Id F</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Values#getIdS <em>Id S</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Values#getIdC <em>Id C</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Values#getIdT <em>Id T</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.Values#getPar <em>Par</em>}</li>
 * </ul>
 *
 * @see br.com.poli.restModel.rest.RestPackage#getValues()
 * @model
 * @generated
 */
public interface Values extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(int)
   * @see br.com.poli.restModel.rest.RestPackage#getValues_Id()
   * @model
   * @generated
   */
  int getId();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Values#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(int value);

  /**
   * Returns the value of the '<em><b>Id B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id B</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id B</em>' attribute.
   * @see #setIdB(String)
   * @see br.com.poli.restModel.rest.RestPackage#getValues_IdB()
   * @model
   * @generated
   */
  String getIdB();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Values#getIdB <em>Id B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id B</em>' attribute.
   * @see #getIdB()
   * @generated
   */
  void setIdB(String value);

  /**
   * Returns the value of the '<em><b>Id F</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id F</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id F</em>' attribute.
   * @see #setIdF(float)
   * @see br.com.poli.restModel.rest.RestPackage#getValues_IdF()
   * @model
   * @generated
   */
  float getIdF();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Values#getIdF <em>Id F</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id F</em>' attribute.
   * @see #getIdF()
   * @generated
   */
  void setIdF(float value);

  /**
   * Returns the value of the '<em><b>Id S</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id S</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id S</em>' attribute.
   * @see #setIdS(String)
   * @see br.com.poli.restModel.rest.RestPackage#getValues_IdS()
   * @model
   * @generated
   */
  String getIdS();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Values#getIdS <em>Id S</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id S</em>' attribute.
   * @see #getIdS()
   * @generated
   */
  void setIdS(String value);

  /**
   * Returns the value of the '<em><b>Id C</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id C</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id C</em>' attribute.
   * @see #setIdC(char)
   * @see br.com.poli.restModel.rest.RestPackage#getValues_IdC()
   * @model
   * @generated
   */
  char getIdC();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Values#getIdC <em>Id C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id C</em>' attribute.
   * @see #getIdC()
   * @generated
   */
  void setIdC(char value);

  /**
   * Returns the value of the '<em><b>Id T</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id T</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id T</em>' attribute.
   * @see #setIdT(String)
   * @see br.com.poli.restModel.rest.RestPackage#getValues_IdT()
   * @model
   * @generated
   */
  String getIdT();

  /**
   * Sets the value of the '{@link br.com.poli.restModel.rest.Values#getIdT <em>Id T</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id T</em>' attribute.
   * @see #getIdT()
   * @generated
   */
  void setIdT(String value);

  /**
   * Returns the value of the '<em><b>Par</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Par</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Par</em>' attribute list.
   * @see br.com.poli.restModel.rest.RestPackage#getValues_Par()
   * @model unique="false"
   * @generated
   */
  EList<String> getPar();

} // Values
