/*
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RestRuntimeModule extends AbstractRestRuntimeModule {
}
