/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.rESTModel.impl;

import br.com.poli.rESTModel.Atrib;
import br.com.poli.rESTModel.RESTModelPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atrib</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.com.poli.rESTModel.impl.AtribImpl#getAtribName <em>Atrib Name</em>}</li>
 *   <li>{@link br.com.poli.rESTModel.impl.AtribImpl#getTipo <em>Tipo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AtribImpl extends MinimalEObjectImpl.Container implements Atrib
{
  /**
   * The default value of the '{@link #getAtribName() <em>Atrib Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtribName()
   * @generated
   * @ordered
   */
  protected static final String ATRIB_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAtribName() <em>Atrib Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtribName()
   * @generated
   * @ordered
   */
  protected String atribName = ATRIB_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getTipo() <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected static final String TIPO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTipo() <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected String tipo = TIPO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtribImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RESTModelPackage.Literals.ATRIB;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAtribName()
  {
    return atribName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAtribName(String newAtribName)
  {
    String oldAtribName = atribName;
    atribName = newAtribName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RESTModelPackage.ATRIB__ATRIB_NAME, oldAtribName, atribName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTipo()
  {
    return tipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTipo(String newTipo)
  {
    String oldTipo = tipo;
    tipo = newTipo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RESTModelPackage.ATRIB__TIPO, oldTipo, tipo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RESTModelPackage.ATRIB__ATRIB_NAME:
        return getAtribName();
      case RESTModelPackage.ATRIB__TIPO:
        return getTipo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RESTModelPackage.ATRIB__ATRIB_NAME:
        setAtribName((String)newValue);
        return;
      case RESTModelPackage.ATRIB__TIPO:
        setTipo((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RESTModelPackage.ATRIB__ATRIB_NAME:
        setAtribName(ATRIB_NAME_EDEFAULT);
        return;
      case RESTModelPackage.ATRIB__TIPO:
        setTipo(TIPO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RESTModelPackage.ATRIB__ATRIB_NAME:
        return ATRIB_NAME_EDEFAULT == null ? atribName != null : !ATRIB_NAME_EDEFAULT.equals(atribName);
      case RESTModelPackage.ATRIB__TIPO:
        return TIPO_EDEFAULT == null ? tipo != null : !TIPO_EDEFAULT.equals(tipo);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (atribName: ");
    result.append(atribName);
    result.append(", Tipo: ");
    result.append(tipo);
    result.append(')');
    return result.toString();
  }

} //AtribImpl
