/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.ide;

import br.com.poli.restModel.ide.AbstractRestIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RestIdeModule extends AbstractRestIdeModule {
}
