/*
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.serializer;

import br.com.poli.restModel.rest.Atrib;
import br.com.poli.restModel.rest.Body;
import br.com.poli.restModel.rest.Elem;
import br.com.poli.restModel.rest.GlobAtrib;
import br.com.poli.restModel.rest.Model;
import br.com.poli.restModel.rest.Parm;
import br.com.poli.restModel.rest.RestPackage;
import br.com.poli.restModel.rest.Values;
import br.com.poli.restModel.services.RestGrammarAccess;
import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class RestSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private RestGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == RestPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case RestPackage.ATRIB:
				sequence_Atrib(context, (Atrib) semanticObject); 
				return; 
			case RestPackage.BODY:
				sequence_Body(context, (Body) semanticObject); 
				return; 
			case RestPackage.ELEM:
				sequence_Elem(context, (Elem) semanticObject); 
				return; 
			case RestPackage.GLOB_ATRIB:
				sequence_GlobAtrib(context, (GlobAtrib) semanticObject); 
				return; 
			case RestPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case RestPackage.PARM:
				sequence_Parm(context, (Parm) semanticObject); 
				return; 
			case RestPackage.VALUES:
				sequence_Values(context, (Values) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Atrib returns Atrib
	 *
	 * Constraint:
	 *     (atribName=ID (Tipo=VALID_TYPES | Tipo=TYPE_NAME) Value=Values?)
	 */
	protected void sequence_Atrib(ISerializationContext context, Atrib semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Body returns Body
	 *
	 * Constraint:
	 *     (elem=Elem | globAtrib=GlobAtrib)
	 */
	protected void sequence_Body(ISerializationContext context, Body semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Elem returns Elem
	 *
	 * Constraint:
	 *     (ClassName=ID package=PackageName? atrib+=Atrib*)
	 */
	protected void sequence_Elem(ISerializationContext context, Elem semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GlobAtrib returns GlobAtrib
	 *
	 * Constraint:
	 *     (atribName=ID (Tipo=VALID_TYPES | Tipo=TYPE_NAME) Value=Values)
	 */
	protected void sequence_GlobAtrib(ISerializationContext context, GlobAtrib semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     body+=Body*
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Parm returns Parm
	 *
	 * Constraint:
	 *     (atribName=ID (Tipo_atri=VALID_TYPES | Tipo_atri=TYPE_NAME))
	 */
	protected void sequence_Parm(ISerializationContext context, Parm semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Values returns Values
	 *
	 * Constraint:
	 *     (
	 *         Id=INT | 
	 *         IdB=BOOL | 
	 *         IdF=FLOAT | 
	 *         IdS=STRING | 
	 *         IdC=CHAR | 
	 *         (IdT=ID (Par+=ID* Par+=ID)?)
	 *     )
	 */
	protected void sequence_Values(ISerializationContext context, Values semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
