/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.rest.impl;

import br.com.poli.restModel.rest.Atrib;
import br.com.poli.restModel.rest.RestPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atrib</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.com.poli.restModel.rest.impl.AtribImpl#getAtribName <em>Atrib Name</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.impl.AtribImpl#getTipo <em>Tipo</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.impl.AtribImpl#getValueInt <em>Value Int</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.impl.AtribImpl#getValueBool <em>Value Bool</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.impl.AtribImpl#getValueFlo <em>Value Flo</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.impl.AtribImpl#getValueStr <em>Value Str</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.impl.AtribImpl#getValueChr <em>Value Chr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AtribImpl extends MinimalEObjectImpl.Container implements Atrib
{
  /**
   * The default value of the '{@link #getAtribName() <em>Atrib Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtribName()
   * @generated
   * @ordered
   */
  protected static final String ATRIB_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAtribName() <em>Atrib Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtribName()
   * @generated
   * @ordered
   */
  protected String atribName = ATRIB_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getTipo() <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected static final String TIPO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTipo() <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected String tipo = TIPO_EDEFAULT;

  /**
   * The default value of the '{@link #getValueInt() <em>Value Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueInt()
   * @generated
   * @ordered
   */
  protected static final int VALUE_INT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getValueInt() <em>Value Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueInt()
   * @generated
   * @ordered
   */
  protected int valueInt = VALUE_INT_EDEFAULT;

  /**
   * The default value of the '{@link #getValueBool() <em>Value Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueBool()
   * @generated
   * @ordered
   */
  protected static final String VALUE_BOOL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValueBool() <em>Value Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueBool()
   * @generated
   * @ordered
   */
  protected String valueBool = VALUE_BOOL_EDEFAULT;

  /**
   * The default value of the '{@link #getValueFlo() <em>Value Flo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueFlo()
   * @generated
   * @ordered
   */
  protected static final float VALUE_FLO_EDEFAULT = 0.0F;

  /**
   * The cached value of the '{@link #getValueFlo() <em>Value Flo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueFlo()
   * @generated
   * @ordered
   */
  protected float valueFlo = VALUE_FLO_EDEFAULT;

  /**
   * The default value of the '{@link #getValueStr() <em>Value Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueStr()
   * @generated
   * @ordered
   */
  protected static final String VALUE_STR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValueStr() <em>Value Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueStr()
   * @generated
   * @ordered
   */
  protected String valueStr = VALUE_STR_EDEFAULT;

  /**
   * The default value of the '{@link #getValueChr() <em>Value Chr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueChr()
   * @generated
   * @ordered
   */
  protected static final char VALUE_CHR_EDEFAULT = '\u0000';

  /**
   * The cached value of the '{@link #getValueChr() <em>Value Chr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueChr()
   * @generated
   * @ordered
   */
  protected char valueChr = VALUE_CHR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtribImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RestPackage.Literals.ATRIB;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAtribName()
  {
    return atribName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAtribName(String newAtribName)
  {
    String oldAtribName = atribName;
    atribName = newAtribName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestPackage.ATRIB__ATRIB_NAME, oldAtribName, atribName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTipo()
  {
    return tipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTipo(String newTipo)
  {
    String oldTipo = tipo;
    tipo = newTipo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestPackage.ATRIB__TIPO, oldTipo, tipo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValueInt()
  {
    return valueInt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValueInt(int newValueInt)
  {
    int oldValueInt = valueInt;
    valueInt = newValueInt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestPackage.ATRIB__VALUE_INT, oldValueInt, valueInt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getValueBool()
  {
    return valueBool;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValueBool(String newValueBool)
  {
    String oldValueBool = valueBool;
    valueBool = newValueBool;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestPackage.ATRIB__VALUE_BOOL, oldValueBool, valueBool));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public float getValueFlo()
  {
    return valueFlo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValueFlo(float newValueFlo)
  {
    float oldValueFlo = valueFlo;
    valueFlo = newValueFlo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestPackage.ATRIB__VALUE_FLO, oldValueFlo, valueFlo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getValueStr()
  {
    return valueStr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValueStr(String newValueStr)
  {
    String oldValueStr = valueStr;
    valueStr = newValueStr;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestPackage.ATRIB__VALUE_STR, oldValueStr, valueStr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public char getValueChr()
  {
    return valueChr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValueChr(char newValueChr)
  {
    char oldValueChr = valueChr;
    valueChr = newValueChr;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestPackage.ATRIB__VALUE_CHR, oldValueChr, valueChr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RestPackage.ATRIB__ATRIB_NAME:
        return getAtribName();
      case RestPackage.ATRIB__TIPO:
        return getTipo();
      case RestPackage.ATRIB__VALUE_INT:
        return getValueInt();
      case RestPackage.ATRIB__VALUE_BOOL:
        return getValueBool();
      case RestPackage.ATRIB__VALUE_FLO:
        return getValueFlo();
      case RestPackage.ATRIB__VALUE_STR:
        return getValueStr();
      case RestPackage.ATRIB__VALUE_CHR:
        return getValueChr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RestPackage.ATRIB__ATRIB_NAME:
        setAtribName((String)newValue);
        return;
      case RestPackage.ATRIB__TIPO:
        setTipo((String)newValue);
        return;
      case RestPackage.ATRIB__VALUE_INT:
        setValueInt((Integer)newValue);
        return;
      case RestPackage.ATRIB__VALUE_BOOL:
        setValueBool((String)newValue);
        return;
      case RestPackage.ATRIB__VALUE_FLO:
        setValueFlo((Float)newValue);
        return;
      case RestPackage.ATRIB__VALUE_STR:
        setValueStr((String)newValue);
        return;
      case RestPackage.ATRIB__VALUE_CHR:
        setValueChr((Character)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RestPackage.ATRIB__ATRIB_NAME:
        setAtribName(ATRIB_NAME_EDEFAULT);
        return;
      case RestPackage.ATRIB__TIPO:
        setTipo(TIPO_EDEFAULT);
        return;
      case RestPackage.ATRIB__VALUE_INT:
        setValueInt(VALUE_INT_EDEFAULT);
        return;
      case RestPackage.ATRIB__VALUE_BOOL:
        setValueBool(VALUE_BOOL_EDEFAULT);
        return;
      case RestPackage.ATRIB__VALUE_FLO:
        setValueFlo(VALUE_FLO_EDEFAULT);
        return;
      case RestPackage.ATRIB__VALUE_STR:
        setValueStr(VALUE_STR_EDEFAULT);
        return;
      case RestPackage.ATRIB__VALUE_CHR:
        setValueChr(VALUE_CHR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RestPackage.ATRIB__ATRIB_NAME:
        return ATRIB_NAME_EDEFAULT == null ? atribName != null : !ATRIB_NAME_EDEFAULT.equals(atribName);
      case RestPackage.ATRIB__TIPO:
        return TIPO_EDEFAULT == null ? tipo != null : !TIPO_EDEFAULT.equals(tipo);
      case RestPackage.ATRIB__VALUE_INT:
        return valueInt != VALUE_INT_EDEFAULT;
      case RestPackage.ATRIB__VALUE_BOOL:
        return VALUE_BOOL_EDEFAULT == null ? valueBool != null : !VALUE_BOOL_EDEFAULT.equals(valueBool);
      case RestPackage.ATRIB__VALUE_FLO:
        return valueFlo != VALUE_FLO_EDEFAULT;
      case RestPackage.ATRIB__VALUE_STR:
        return VALUE_STR_EDEFAULT == null ? valueStr != null : !VALUE_STR_EDEFAULT.equals(valueStr);
      case RestPackage.ATRIB__VALUE_CHR:
        return valueChr != VALUE_CHR_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (atribName: ");
    result.append(atribName);
    result.append(", Tipo: ");
    result.append(tipo);
    result.append(", ValueInt: ");
    result.append(valueInt);
    result.append(", ValueBool: ");
    result.append(valueBool);
    result.append(", ValueFlo: ");
    result.append(valueFlo);
    result.append(", ValueStr: ");
    result.append(valueStr);
    result.append(", ValueChr: ");
    result.append(valueChr);
    result.append(')');
    return result.toString();
  }

} //AtribImpl
