/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.rest.impl;

import br.com.poli.restModel.rest.Body;
import br.com.poli.restModel.rest.Elem;
import br.com.poli.restModel.rest.GlobAtrib;
import br.com.poli.restModel.rest.RestPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Body</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.com.poli.restModel.rest.impl.BodyImpl#getElem <em>Elem</em>}</li>
 *   <li>{@link br.com.poli.restModel.rest.impl.BodyImpl#getGlobAtrib <em>Glob Atrib</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BodyImpl extends MinimalEObjectImpl.Container implements Body
{
  /**
   * The cached value of the '{@link #getElem() <em>Elem</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElem()
   * @generated
   * @ordered
   */
  protected Elem elem;

  /**
   * The cached value of the '{@link #getGlobAtrib() <em>Glob Atrib</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGlobAtrib()
   * @generated
   * @ordered
   */
  protected GlobAtrib globAtrib;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BodyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RestPackage.Literals.BODY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Elem getElem()
  {
    return elem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetElem(Elem newElem, NotificationChain msgs)
  {
    Elem oldElem = elem;
    elem = newElem;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RestPackage.BODY__ELEM, oldElem, newElem);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setElem(Elem newElem)
  {
    if (newElem != elem)
    {
      NotificationChain msgs = null;
      if (elem != null)
        msgs = ((InternalEObject)elem).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RestPackage.BODY__ELEM, null, msgs);
      if (newElem != null)
        msgs = ((InternalEObject)newElem).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RestPackage.BODY__ELEM, null, msgs);
      msgs = basicSetElem(newElem, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestPackage.BODY__ELEM, newElem, newElem));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GlobAtrib getGlobAtrib()
  {
    return globAtrib;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGlobAtrib(GlobAtrib newGlobAtrib, NotificationChain msgs)
  {
    GlobAtrib oldGlobAtrib = globAtrib;
    globAtrib = newGlobAtrib;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RestPackage.BODY__GLOB_ATRIB, oldGlobAtrib, newGlobAtrib);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setGlobAtrib(GlobAtrib newGlobAtrib)
  {
    if (newGlobAtrib != globAtrib)
    {
      NotificationChain msgs = null;
      if (globAtrib != null)
        msgs = ((InternalEObject)globAtrib).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RestPackage.BODY__GLOB_ATRIB, null, msgs);
      if (newGlobAtrib != null)
        msgs = ((InternalEObject)newGlobAtrib).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RestPackage.BODY__GLOB_ATRIB, null, msgs);
      msgs = basicSetGlobAtrib(newGlobAtrib, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RestPackage.BODY__GLOB_ATRIB, newGlobAtrib, newGlobAtrib));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RestPackage.BODY__ELEM:
        return basicSetElem(null, msgs);
      case RestPackage.BODY__GLOB_ATRIB:
        return basicSetGlobAtrib(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RestPackage.BODY__ELEM:
        return getElem();
      case RestPackage.BODY__GLOB_ATRIB:
        return getGlobAtrib();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RestPackage.BODY__ELEM:
        setElem((Elem)newValue);
        return;
      case RestPackage.BODY__GLOB_ATRIB:
        setGlobAtrib((GlobAtrib)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RestPackage.BODY__ELEM:
        setElem((Elem)null);
        return;
      case RestPackage.BODY__GLOB_ATRIB:
        setGlobAtrib((GlobAtrib)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RestPackage.BODY__ELEM:
        return elem != null;
      case RestPackage.BODY__GLOB_ATRIB:
        return globAtrib != null;
    }
    return super.eIsSet(featureID);
  }

} //BodyImpl
