/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.tests;

import br.com.poli.restModel.rest.Model;
import br.com.poli.restModel.tests.RestInjectorProvider;
import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(RestInjectorProvider.class)
@SuppressWarnings("all")
public class RestParsingTest {
  @Inject
  private ParseHelper<Model> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Request{ ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("#Comentario");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("Host : String ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("Entity{");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("Atributo : Tipo");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("Metodo() : Tipo");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("MetodoImplementadoJava() : Tipo");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("Entity2{");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("Atributo : String : \"Olá\"");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("Atributo : int : 90");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("Metodo() : Tipo\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("MetodoImplementadoJava() : Tipo");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
