/*
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.ide

import br.com.poli.restModel.RestRuntimeModule
import br.com.poli.restModel.RestStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RestIdeSetup extends RestStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RestRuntimeModule, new RestIdeModule))
	}
	
}
