/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.scoping;

import br.com.poli.restModel.scoping.AbstractRestScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class RestScopeProvider extends AbstractRestScopeProvider {
}
