/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.restModel.ui;

import br.com.poli.restModel.ui.AbstractRestUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RestUiModule extends AbstractRestUiModule {
  public RestUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
