/**
 * generated by Xtext 2.15.0
 */
package br.com.poli.validation;

import br.com.poli.validation.AbstractRESTModelValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RESTModelValidator extends AbstractRESTModelValidator {
}
